# Generated by Django 5.2.6 on 2025-09-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('phone', models.PositiveIntegerField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
