# Generated by Django 5.2.6 on 2025-09-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contactmodel_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
