# Generated by Django 5.2.6 on 2025-09-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_contactmodel_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='address',
            new_name='message',
        ),
    ]
