# Generated by Django 5.2.6 on 2025-09-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_address_contactmodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
